seq = "CCGTAAGCTCTTAAGGCTCTGCACGCACACGCCGACGAACCCTCGAGTGGGCTAGGTCATGCTGCATGTAAGCAGGTCTCCTATAGCGGGAGCCTGCCGAACTTGCTGACTGCGTTCATTACTTGGATACTGTCCCGGCTTACCCATTGCCTAACCCGCGCAATCGGGCCTATTCAGTCCAGAATCGCGGCAACGCTATCATTGAAGGTCTATGGCCATGTCAGTCGACCCCTGTAGCGTACAATTCATGTTGGTGACGGACTAGGTATTGAGGAGATTGGTCTATTCATTACTTATTCCTTCTGGTAGACGCCAGATCAGCGCAGATTGGCCCCAACACTAGAAAATACGTATTCGTAAGCATGAGTGTAACAGATAAACAACACCCACCGGAAAAATTAGTCTTATAGCAGACTGAGATCGCCCGCACCTCAAGTATACGCGTAGCTCGTAGATACCCAGGGAATACTCAGTCGACTGGGATGTGCGTCGTCCGCACCTTTGCGACTAACGTTGGAATCCAACGAACGTCGCCAGGGTCTACCAGTTATGAAGCAGGACCAGCATGGAAAGACCAGGTCAATAAGCCAACCTACGGATTGGATGCAAACGACCTCATGTGCGGCGCGAAGGATTAGCCGCCGTAAGGCTCCTGTCCCTACGCCAATATGTCACCCATCGGACTGCCCTCGACTCACCCATTGAGTAGGTATCTGGCTACCAGTGGACATTTGATGGAATTCCCCGTGCGATGACCAAAACCTCCGACTCAGGCTCATTGTAGGCTTCCGTCGTAATATGACC"

reverse = seq[::-1]

newseq = ""

for nt in reverse:
    if nt == "A":
        newseq += "T"
    elif nt == "T":
        newseq += "A"
    elif nt == "C":
        newseq += "G"
    elif nt == "G":
        newseq += "C"

print(newseq)
